name: $pluginName
version: $version
main: live.myoun.aestus.AestusPlugin
api-version: $apiVersion

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.10

commands:
  break:
    description: 선택된 범위 내 블럭들을 부숩니다.
  cancel:
    description: 블럭 파괴를 취소합니다.
  st:
    description: 특정 작업을 멈춥니다.
  undo:
    description: 블럭 파괴를 되돌립니다.
  cloner:
    description: 선택된 범위 내 블럭들을 복사합니다.