name: $pluginName
version: $version
main: live.myoun.aestus.AestusPlugin
api-version: 1.18

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.10

commands:
  break:
    description: break it
  cancel:
    description: canel break command
  st:
    description: stop specific task
  undo:
    description: undo break
  cloner:
    description: clone blocks