name: Aestus
version: 1.3.0
main: live.myoun.aestus.AestusPlugin
api-version: 1.17

commands:
  break:
    description: break it
  cancel:
    description: canel break command
  st:
    description: stop specific task