name: $pluginName
version: $version
main: live.myoun.aestus.AestusPlugin
api-version: 1.17

commands:
  break:
    description: break it
  cancel:
    description: canel break command
  st:
    description: stop specific task
  undo:
    description: undo break